config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'

  get '/about' => 'pages#about'
  get '/contact/new' => 'contacts#new'
  get '/submit' => 'pages#submit'
  get '/microposts/index' => 'microposts#index'
  get '/signup'  => 'users#new'
  get    '/login'   => 'sessions#new'
  post   '/login'   => 'sessions#create'
  delete '/logout'  => 'sessions#destroy'

  get 'password_resets/new'
  get 'password_resets/edit'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  
  resources :microposts,          only: [:create]

  resources :contacts

  
  MyApp::Application.routes.draw do
   get "*any", via: :all, to: "errors#not_found"
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="google-site-verification" content="JdcDauELutsZeMY8eVhsUOaafkKudc47uPGo4q16a8M" />
  <title>ChemCoder</title>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
</head>
<body>

<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: 'navbar-brand' do %>
	      <i class="fa fa-code"></i>
	      ChemCoder
      <% end %>
    </div>
    <div class="collapse navbar-collapse" id="main-nav-collapse">
<!--       <ul class="nav navbar-nav">
        <li><%= link_to "About Us", about_path %></li>
        <li><%= link_to "Contact Us", new_contact_path %></li>
      </ul> -->

    <%= form_tag(microposts_index_path, :method => "get", id: "search-form", class: "form-inline navbar-form navbar-left", role: "search") do %>
    <div class="form-group">
      <%= text_field_tag :search, params[:search], placeholder: "Search input files for...", class:"form-control" %>
    </div>
      <%= submit_tag "Search", class:"btn btn-default", :name => nil %>

  <% end %>


<div class="nav navbar-nav navbar-right">
  <% if logged_in? %>
        <%= link_to "Post Code", submit_path, class: 'btn btn-warning navbar-btn', method: :get %>
        <%= link_to "Profile", current_user, class: "btn btn-primary navbar-btn" %>
        <%= link_to "Logout",logout_path, method: :delete, class: "btn btn-primary navbar-btn" %>
  <% else %>
        <%= link_to "Login", login_path, class: 'btn btn-primary navbar-btn' %>
        <%= link_to "Signup", signup_path, class: 'btn btn-success navbar-btn' %> 
  <% end %>
      </div> 


    </div><!-- /.navbar-collapse -->
  </div>
</nav>

<div class="container">

  <% flash.each do |key,value| %>
  <!--  Accrording to Rails documentation, content_tag generates HTML of type (div) surrounding the content (value, class). We use this to strucutre the alert according to Bootstrap requirements.
  
        e.x. <div class="alert alert-success">"Message sent"</div>
  -->

    <%= content_tag :div, value, class:"alert alert-#{key}" %>
  <% end %>

	<%= yield %>
        <%= debug(params) if Rails.env.development? %> <!-- outputs some debugging info when in development only -->
</div>



  
<nav class="navbar navbar-default text-center" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to root_path, class: 'navbar-brand' do %>
        <i class="fa fa-code"></i>
        ChemCoder
      <% end %>
    </div>

    <div class="nav navbar-nav navbar-right">
       <%= link_to "Problems?  Contact us.", new_contact_path, class:"navbar-text"%>
      <p class="navbar-text">Created in 2014 by Ryan Zaari.</p>
    </div>
  </div>
</nav>




</body>
</html>